[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --always-print-stacktrace --connect-under-reset --chip STM32F411CEUx"
linker = "flip-link"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
